name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for trusted publishing with OIDC
      contents: write   # To allow checkout and potential pushes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      # Uncomment the following section if your build step might modify files and you want to push those changes
      # - name: Commit and push changes
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "Automated build output"
      #     git push

      - name: Publish to PyPI via trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true  # Optional: skip if version already exists
